In [3]:
"""
Created on Fri Jan 27 16:36:59 2023

@author: andre_trierveiler
"""

from bs4 import BeautifulSoup
import base64
import requests
import pandas as pd
import webbrowser

producao_url = 'https://api.anbima.com.br/'
sandbox_url = 'https://api-sandbox.anbima.com.br/'
id_url = "https://api.anbima.com.br/oauth/access-token"

### Define se dados vem de ambiente de producao ou sandbox ###
producao = True

if producao:
  url = producao_url
  client_id = "wRGlvlj1bOW3"
  client_secret = "l4riAuRd0CUL"
  client_credentials = "wRGlvlj1bOW3:l4riAuRd0CUL"

else:
  url = sandbox_url
  client_id = "nZqmOGEuh6bg"
  client_secret = "BMXhChrji7ca"
  client_credentials = "nZqmOGEuh6bg:BMXhChrji7ca"


client_credentials = client_credentials.encode('ascii')
senhabytes = base64.b64encode(client_credentials)
senha = base64.b64decode(senhabytes)


def conectar(client_id, client_secret, client_credentials, url=url):
    client_credentials = client_credentials.encode('ascii')
    senhabytes = base64.b64encode(client_credentials)
    senha = base64.b64decode(senhabytes)

    body = {"grant_type": "client_credentials" }

    headers = {
            'content-type': 'application/json',
            'Authorization': 'Basic d1JHbHZsajFiT1czOmw0cmlBdVJkMENVTA=='}
     
    request = requests.post(id_url, headers=headers, json=body, allow_redirects=True)
    informacoes = request.json()
    token = informacoes['access_token']  
    
    return { "content-type": "application/json",
            "client_id": f"{client_id}",
            "access_token": f"{token}"}

### Header Sandbox ###   
headers2 = conectar('nZqmOGEuh6bg', 'BMXhChrji7ca','nZqmOGEuh6bg:BMXhChrji7ca', url)

####  Header produção###
headers3 = conectar('wRGlvlj1bOW3', 'l4riAuRd0CUL','wRGlvlj1bOW3:l4riAuRd0CUL', url)


"""
headers = {
            'content-type': 'application/json',
            'Authorization': 'Basic d1JHbHZsajFiT1czOmw0cmlBdVJkMENVTA=='}
request = requests.post('https://api.anbima.com.br/oauth/access-token', headers=headers, json=body, allow_redirects=True)
informacoes = request.json()
token = informacoes['access_token']  
"""

"\nheaders = {\n            'content-type': 'application/json',\n            'Authorization': 'Basic d1JHbHZsajFiT1czOmw0cmlBdVJkMENVTA=='}\nrequest = requests.post('https://api.anbima.com.br/oauth/access-token', headers=headers, json=body, allow_redirects=True)\ninformacoes = request.json()\ntoken = informacoes['access_token']  \n"

In [18]:
df_cadastro = pd.DataFrame() 
size = 1000
pages = 50
for i in range(1,pages):
    fundos_http = f'https://api.anbima.com.br/feed/fundos/v1/fundos?page={i}&size=1000' #tamanho máximo 1000, 32 paginas totais
    fundos = requests.get(fundos_http, headers=headers3)
    fundos_json = fundos.json()
    df = pd.json_normalize(fundos_json['content'])
    df['page'] = i
    df_cadastro = pd.concat([df_cadastro,df])
    if len(df) < 1000:
        break
df_cadastro = df_cadastro.reset_index(drop=True)
del df_cadastro['nome_fantasia_2']

cnpjs = ['16844890000158',
'07861554000122',
'07442078000105',
'08980715000160',
'13482675000166',
'05104498000156',
'10824344000179',
'10740658000193',
'10646895000190',
'10577516000157',
'02935723000108',
'04215425000179',
'10474513000198',
'08927393000195',
'32292548000149',
'11180605000128',
'14504578000190',
'04385278000185',
'11087118000115',
'16403465000123',
'09326708000101']

lista = df_cadastro[['codigo_fundo','nome_fantasia']][df_cadastro['cnpj_fundo'].isin(cnpjs)].reset_index(drop=True)


df_dados_cadastrais = pd.DataFrame() 
df_movimentacao = pd.DataFrame()
df_prestadores = pd.DataFrame()
df_cota = pd.DataFrame()
df_documentos = pd.DataFrame()
df_taxas = pd.DataFrame()
df_taxas_historico = pd.DataFrame()

abre_regulamento = False

for codigo_fundo in lista.codigo_fundo:
    nome_fantasia = lista.nome_fantasia[lista['codigo_fundo'] == codigo_fundo].reset_index(drop=True)[0]
    fundos_det_http = f'https://api.anbima.com.br/feed/fundos/v1/fundos/{codigo_fundo}'
    fundos_det = requests.get(fundos_det_http, headers=headers3)
    fundos_det_json = fundos_det.json()
    dados_cadastrais = pd.json_normalize(fundos_det_json['dados-cadastrais'])
    df_dados_cadastrais = pd.concat([df_dados_cadastrais,dados_cadastrais])
    del df_dados_cadastrais['nome_fantasia_2']
    
    movimentacao = pd.json_normalize(fundos_det_json['movimentacao'])
    movimentacao['codigo_fundo'] = codigo_fundo
    movimentacao ['nome_fantasia'] = nome_fantasia
    df_movimentacao = pd.concat([df_movimentacao,movimentacao])
    
    
    prestadores = pd.json_normalize(fundos_det_json['prestadores'])
    prestadores['gestores_principal'] = pd.json_normalize(prestadores.gestores[0][0]).nome[0]
    prestadores['codigo_fundo'] = codigo_fundo
    prestadores['nome_fantasia'] = nome_fantasia
    df_prestadores = pd.concat([df_prestadores,prestadores])
    
    cota =  pd.json_normalize(fundos_det_json['serie_historica'])
    cota['codigo_fundo'] = codigo_fundo
    cota['nome_fantasia'] = nome_fantasia
    df_cota = pd.concat([df_cota,cota])
    
    taxas = pd.json_normalize(fundos_det_json['taxas'])
    taxas['codigo_fundo'] = codigo_fundo
    taxas['nome_fantasia'] = nome_fantasia
    df_taxas = pd.concat([df_taxas,taxas])
    
    documentos = pd.json_normalize(fundos_det_json['documentos'])
    documentos['codigo_fundo'] = codigo_fundo
    documentos['nome_fantasia'] = nome_fantasia
    df_documentos  = pd.concat([df_documentos,documentos])
    if abre_regulamento is True:
        webbrowser.open(documentos.url[0],new=2)   
        
    taxas_historico = pd.json_normalize(fundos_det_json['historico_taxas'])
    taxas_historico['codigo_fundo'] = codigo_fundo
    taxas_historico['nome_fantasia'] = nome_fantasia
    df_taxas_historico = pd.concat([df_dados_cadastrais,dados_cadastrais])

    
teste = pd.merge(df_dados_cadastrais,df_cota, on='codigo_fundo')

In [19]:
display(df_cadastro)

,codigo_fundo,nome_fantasia,cnpj_fundo,classe_anbima,situacao_atual,data_inicio_divulgacao_cota,data_atualizacao,page
0,129739,ODESSA RF CRED PRIV FI,05615621000101,Renda Fixa,A,2004-07-22,2022-12-13T18:21:00,1
1,129763,CA PR 193 FIF CIC MULT CRED PR RESP LIM,06235305000169,Multimercados,A,2004-07-28,2024-05-21T16:34:00,1
2,129828,SAFRA EXECUTIVE MAX RF FC FI,00180995000110,Renda Fixa,A,2004-07-28,2023-08-16T16:52:00,1
3,129844,SUPORTE FI MULT LP,05900607000141,Multimercados,A,2004-04-30,2024-04-24T16:09:00,1
4,129860,FIAT PREV FIF ESPE CONST CIC RF RESP LIM,03821440000106,Previdência,A,2004-07-30,2024-05-22T16:19:00,1
...,...,...,...,...,...,...,...,...
32067,759147,VEDODI FIF EM ACOES - RESP LIMITADA,54990769000123,Ações,A,NaN,2024-05-31T16:19:00,33
32068,759155,PRETIUM 3 FIF MULT CRED PRIV RESP LIM,55048708000104,Multimercados,A,NaN,2024-05-31T16:19:00,33
32069,759163,LEVON IV FIF MULT CRED PRIV RESP LIM,55065045000136,Multimercados,A,NaN,2024-05-31T16:19:00,33
32070,759171,IBIU LS CLAS COTA INVES COTA INVES ACOES,54546087000126,Ações,A,NaN,2024-05-31T16:19:00,33
32071,759341,CLAS UNIC COTA DO COMO FI MULT CRED PRIV,55064130000180,Multimercados,A,NaN,2024-05-31T16:26:00,33

In [20]:
display(df_dados_cadastrais)

,codigo_fundo,nome_fantasia,razao_social,cnpj_fundo,codigo_isin,data_primeiro_aporte,data_inicio,classe_anbima,tipo_anbima,classe_cvm,...,aberto_estatutariamente,tributacao_alvo,data_atualizacao,situacao_atual,multigestor,aplicacao_automatica,foco_atuacao,esg,fundo_adaptado_icvm_175,responsabilidade_ltda
0,133485,SANTANDER RENDA FIXA INFLACAO VIP FC FI,SANTANDER RENDA FIXA INFLAÇÃO VIP FUNDO DE INV...,04385278000185,BRAFX1CTF008,2001-09-06,2001-09-06,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-04-18T17:19:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,195782,BB RENDA FIXA LP INFLACAO FC,BB RENDA FIXA LP INFLAÇÃO FUNDO DE INVESTIMENT...,08980715000160,NaN,2007-10-03,2007-10-03,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2021-09-23T16:54:00,A,Feeder,Não se Aplica,Não,N,N,Não
0,196320,ITAU PRIVATE RENDA FIXA IMA-B FC,ITAÚ PRIVATE RENDA FIXA IMA-B FUNDO DE INVEST...,08927393000195,BRIFL1CTF004,2007-10-10,2007-10-10,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-05-30T13:37:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,212873,SUL AMERICA INFLATIE FI RENDA FIXA LP,SUL AMERICA INFLATIE FDO DE INVEST RENDA FIXA ...,09326708000101,BRIFL2CTF002,2008-07-11,2008-07-11,Renda Fixa,Renda Fixa Duração Alta Soberano,Renda Fixa,...,S,Longo Prazo,2023-10-11T17:07:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,236365,CAIXA FC NOVO BRASIL RF IMA-B LP,FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE IN...,10646895000190,BRCA29CTF005,2009-10-27,2009-10-27,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-09-04T16:40:00,A,Feeder,Não se Aplica,Não,N,N,Não
0,237779,ITAU INSTITUCIONAL RF IMA-B FC,ITAÚ INSTITUCIONAL RENDA FIXA IMA-B FUNDO DE I...,10474513000198,BRITR3CTF008,2009-11-26,2009-11-26,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-03-09T17:24:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,239429,SANTANDER RENDA FIXA IMA-B FI LP,SANTANDER RENDA FIXA IMA-B FUNDO DE INVESTIMEN...,11180605000128,NaN,2009-12-09,2009-12-09,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-03-03T15:40:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,240141,SICREDI INSTIT IMA-B FIC FI RF LP,SICREDI – FUNDO DE INVESTIMENTO EM COTAS DE FU...,11087118000115,NaN,2009-12-18,2009-12-18,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-12-21T17:11:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,242896,BB PREVIDENCIARIO RF IMA B FI,BB PREVIDENCIARIO RENDA FIXA IMA B FUNDO DE IN...,07861554000122,NaN,2006-03-09,2006-03-09,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Não Aplicável,2021-09-22T18:09:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,242901,BB PREVIDENCIARIO RF IMA B TIT PUBL FI,BB PREVIDENCIARIO RENDA FIXA IMA B TIT PUBL FI,07442078000105,NaN,2005-06-24,2005-06-24,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Não Aplicável,2021-09-22T18:09:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,244120,FI CAIXA BRASIL IMA B TP RF LP,CAIXA FI BRASIL IMA B TIT PUBL RF LP,10740658000193,BRFIB3CTF002,2010-03-08,2010-03-08,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-05-26T17:27:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,246026,BRB FIC FIRF LP IMA-B,BRB FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS D...,10824344000179,NaN,2010-04-01,2010-04-01,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-08-11T11:07:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,273449,BB RF LP INFLACAO IMA-B PRIVATE FC,BB RENDA FIXA LP INFLAÇÃO IMA-B PRIVATE FUNDO ...,13482675000166,NaN,2011-05-03,2011-05-03,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2021-09-23T16:55:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,294081,SANTANDER RF IMA-B PREMIUM FC FI LP,SANTANDER RENDA FIXA IMA-B PREMIUM FUNDO DE IN...,14504578000190,BRTPB2CTF009,2011-12-29,2011-12-29,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-10-16T17:13:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,302570,CAIXA FIC PERFORMANCE IMA B RF LP,CAIXA FIC PERFORMANCE IMA B RF LP,10577516000157,BRIMB8CTF002,2012-05-02,2012-05-02,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-05-24T10:56:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,310980,SICREDI IPCA + FIC FI RF LP,SICREDI FUNDO DE INVESTIMENTO EM COTAS DE FUND...,16403465000123,NaN,2012-08-15,2012-08-15,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-12-21T17:11:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,316423,BANRISUL FOCO IMA B FI RF LP,BANRISUL FOCO IMA B FUNDO DE INVESTIMENTO REND...,16844890000158,NaN,2012-10-01,2012-10-01,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-03-03T19:00:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não
0,497320,ITAU VERTICE COMPROMISSO INFLACAO RF FC,ITAÚ VÉRTICE COMPROMISSO INFLAÇÃO RENDA FIXA F...,32292548000149,BR01HFCTF002,2019-05-10,2019-05-10,Renda Fixa,Renda Fixa Indexados,Renda Fixa,...,S,Longo Prazo,2023-03-08T08:16:00,A,Não se Aplica,Não se Aplica,Não,N,N,Não

In [22]:
data_inicial = '2024-01-01'
data_final = '2024-12-31'
df_fundos_hist = pd.DataFrame()
for codigo_fundo in lista.codigo_fundo:
    nome_fantasia = lista.nome_fantasia[lista['codigo_fundo'] == codigo_fundo].reset_index(drop=True)[0]
    fundos_hist_http = f'https://api.anbima.com.br/feed/fundos/v1/fundos/{codigo_fundo}/serie-historica?data-inicio={data_inicial}&data-fim={data_final}'
    fundos_hist = requests.get(fundos_hist_http, headers=headers3)
    fundos_hist_json = fundos_hist.json()
    fundos_hist = pd.json_normalize(fundos_hist_json['serie_historica'])
    fundos_hist['codigo_fundo'] = codigo_fundo
    fundos_hist['nome_fantasia'] = nome_fantasia
    df_fundos_hist = pd.concat([df_fundos_hist,fundos_hist])

In [23]:
display(df_fundos_hist)

,patrimonio_liquido,valor_cota,captacao,resgate,numero_cotistas,codigo_moeda,data_atualizacao,data_referencia,resgate_detalhamento.resgates_ir,resgate_detalhamento.resgates_cotista,codigo_fundo,nome_fantasia
0,2.534255e+08,153.862385,217000.00,523758.11,5759,BRL,2024-05-31T15:58:00,2024-05-29,0.0,523758.11,133485,SANTANDER RENDA FIXA INFLACAO VIP FC FI
1,2.548505e+08,154.156408,5100.00,464602.22,5769,BRL,2024-05-29T17:27:00,2024-05-28,0.0,464602.22,133485,SANTANDER RENDA FIXA INFLACAO VIP FC FI
2,2.551253e+08,154.044837,25791.28,1828832.46,5789,BRL,2024-05-28T16:46:00,2024-05-27,0.0,1828832.46,133485,SANTANDER RENDA FIXA INFLACAO VIP FC FI
3,2.570480e+08,154.116610,438982.00,2181792.22,5813,BRL,2024-05-27T15:53:00,2024-05-24,0.0,2181792.22,133485,SANTANDER RENDA FIXA INFLACAO VIP FC FI
4,2.589356e+08,154.202848,120100.00,642050.32,5835,BRL,2024-05-24T16:49:00,2024-05-23,0.0,642050.32,133485,SANTANDER RENDA FIXA INFLACAO VIP FC FI
...,...,...,...,...,...,...,...,...,...,...,...,...
98,2.886809e+07,14.471197,0.00,0.00,19,BRL,2024-01-09T17:18:00,2024-01-08,0.0,0.00,497320,ITAU VERTICE COMPROMISSO INFLACAO RF FC
99,2.892886e+07,14.501660,0.00,0.00,19,BRL,2024-01-08T16:04:00,2024-01-05,0.0,0.00,497320,ITAU VERTICE COMPROMISSO INFLACAO RF FC
100,2.894545e+07,14.509978,0.00,0.00,19,BRL,2024-01-05T17:26:00,2024-01-04,0.0,0.00,497320,ITAU VERTICE COMPROMISSO INFLACAO RF FC
101,2.900376e+07,14.539204,0.00,0.00,19,BRL,2024-01-04T16:50:00,2024-01-03,0.0,0.00,497320,ITAU VERTICE COMPROMISSO INFLACAO RF FC
102,2.899133e+07,14.532977,0.00,0.00,19,BRL,2024-01-03T15:54:00,2024-01-02,0.0,0.00,497320,ITAU VERTICE COMPROMISSO INFLACAO RF FC

In [29]:
df_fundos_hist.data_referencia = pd.to_datetime(df_fundos_hist.data_referencia, format='%Y-%m-%d')
#df_fundos_hist.data_atualizacao = pd.to_datetime(df_fundos_hist.data_atualizacao, format='%Y-%m-%d')
df_fundos_hist.dtypes

patrimonio_liquido                              float64
valor_cota                                      float64
captacao                                        float64
resgate                                         float64
numero_cotistas                                   int64
codigo_moeda                                     object
data_atualizacao                                 object
data_referencia                          datetime64[ns]
resgate_detalhamento.resgates_ir                float64
resgate_detalhamento.resgates_cotista           float64
codigo_fundo                                     object
nome_fantasia                                    object
dtype: object

In [30]:
import datetime
from datetime import datetime as dt
from datetime import timedelta
import numpy as np
import matplotlib.dates as mdates
import matplotlib.ticker as mtick
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objs as go
import plotly.offline as py
import plotly


variables = ['patrimonio_liquido','numero_cotistas']
resample = 'W'

df_plot_m = df_fundos_hist.melt(id_vars=['data_referencia','codigo_fundo','nome_fantasia'], value_vars=variables)
df_plot_m.sort_values(by=['data_referencia','codigo_fundo','variable'], inplace=True)
df_plot_m['date_str'] = df_plot_m.data_referencia.dt.strftime('%Y-%m-%d')

df_plot_m = df_plot_m.set_index('data_referencia').groupby(['codigo_fundo','variable']).resample(resample).ffill()
del df_plot_m['codigo_fundo']
del df_plot_m['variable']
df_plot_m = df_plot_m.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')


fig = px.line(df_plot_m
               , y='value'
               , x='data_referencia'
               #, animation_frame=df_plot_m.date_str
               #, animation_group="group_by"
               #, facet_col_wrap=col_wrap       
               #, facet_col = col
               , facet_col_wrap=3      
               , facet_col = 'variable'   
               , color='nome_fantasia'
               , hover_name='nome_fantasia'
               #, labels={'value':'Number of Cases','day_number':"Days Since "+ str(threshold) +"th Case",'date':'Date', 'name':'City'}
               #, range_y=[0.1, df_plot_m.value.max()+5000]
               #, range_x = [df_plot_m.date.min(),df_plot_m.date.max()]
               #, text=df_plot_m[group_by]
               #, size=1
               , title='teste'
               )
fig.update_yaxes(matches=None) 
#fig.update_xaxes(matches=None)
fig.update_yaxes(showticklabels=True)

fig.show()

C:\Users\andre\anaconda3\Lib\site-packages\_plotly_utils\basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [41]:
df_fundos_hist['captacao_acumulada'] = df_fundos_hist['captacao_acumulada'].fillna(0)
df_fundos_hist['resgate_acumulado'] = df_fundos_hist['resgate_acumulado'].fillna(0)
df_fundos_hist['captacao_acumulada'] = df_fundos_hist.groupby('codigo_fundo').captacao.rolling(60).sum().reset_index(0,drop=True)  
df_fundos_hist['resgate_acumulado'] = df_fundos_hist.groupby('codigo_fundo').resgate.rolling(60).sum().reset_index(0,drop=True)
df_fundos_hist['captacao_liquida_acumulda'] = df_fundos_hist['captacao_acumulada'] -df_fundos_hist['resgate_acumulado']  


variables = ['captacao_acumulada','resgate_acumulado']
resample = 'W'

df_plot_m = df_fundos_hist.melt(id_vars=['data_referencia','codigo_fundo','nome_fantasia'], value_vars=variables)
df_plot_m.sort_values(by=['data_referencia','codigo_fundo','variable'], inplace=True)
df_plot_m['date_str'] = df_plot_m.data_referencia.dt.strftime('%Y-%m-%d')

df_plot_m = df_plot_m.set_index('data_referencia').groupby(['codigo_fundo','variable']).resample(resample).ffill()
del df_plot_m['codigo_fundo']
del df_plot_m['variable']
df_plot_m = df_plot_m.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')


fig = px.line(df_plot_m
               , y='value'
               , x='data_referencia'
               #, animation_frame=df_plot_m.date_str
               #, animation_group="group_by"
               #, facet_col_wrap=col_wrap       
               #, facet_col = col
               , facet_col_wrap=3      
               , facet_col = 'variable'   
               , color='nome_fantasia'
               , hover_name='nome_fantasia'
               #, labels={'value':'Number of Cases','day_number':"Days Since "+ str(threshold) +"th Case",'date':'Date', 'name':'City'}
               #, range_y=[0.1, df_plot_m.value.max()+5000]
               #, range_x = [df_plot_m.date.min(),df_plot_m.date.max()]
               #, text=df_plot_m[group_by]
               #, size=1
               , title='teste'
               )
fig.update_yaxes(matches=None) 
#fig.update_xaxes(matches=None)
fig.update_yaxes(showticklabels=True)

fig.show()

C:\Users\andre\anaconda3\Lib\site-packages\_plotly_utils\basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [35]:
display(df_plot_m)

,codigo_fundo,variable,data_referencia,nome_fantasia,value,date_str
0,133485,captacao_acumulada,2024-01-07,SANTANDER RENDA FIXA INFLACAO VIP FC FI,58457115.06,2024-01-05
1,133485,captacao_acumulada,2024-01-14,SANTANDER RENDA FIXA INFLACAO VIP FC FI,NaN,2024-01-12
2,133485,captacao_acumulada,2024-01-21,SANTANDER RENDA FIXA INFLACAO VIP FC FI,NaN,2024-01-19
3,133485,captacao_acumulada,2024-01-28,SANTANDER RENDA FIXA INFLACAO VIP FC FI,NaN,2024-01-26
4,133485,captacao_acumulada,2024-02-04,SANTANDER RENDA FIXA INFLACAO VIP FC FI,NaN,2024-02-02
...,...,...,...,...,...,...
787,497320,resgate_acumulado,2024-05-05,ITAU VERTICE COMPROMISSO INFLACAO RF FC,NaN,2024-05-03
788,497320,resgate_acumulado,2024-05-12,ITAU VERTICE COMPROMISSO INFLACAO RF FC,NaN,2024-05-10
789,497320,resgate_acumulado,2024-05-19,ITAU VERTICE COMPROMISSO INFLACAO RF FC,NaN,2024-05-17
790,497320,resgate_acumulado,2024-05-26,ITAU VERTICE COMPROMISSO INFLACAO RF FC,NaN,2024-05-24
791,497320,resgate_acumulado,2024-06-02,ITAU VERTICE COMPROMISSO INFLACAO RF FC,NaN,2024-05-29